const QUESTIONS_PER_GAME_NUM = 10
const CORRECT_CHOISE_POINTS = 50
const GAME_INTRO_LENGTH_SECS = 3
const QUESTION_TIMEOUT_SECS = 10
const QUESTION_REVEAL_RESULT_MS = 2500
const MUSIC_DATA_COUNTRY = 'it'
const GAME_STATES = Object.freeze({ 'preGame': 1, 'inGame': 2, 'postGame': 3 })

export {
  QUESTIONS_PER_GAME_NUM,
  CORRECT_CHOISE_POINTS,
  GAME_INTRO_LENGTH_SECS,
  QUESTION_TIMEOUT_SECS,
  QUESTION_REVEAL_RESULT_MS,
  MUSIC_DATA_COUNTRY,
  GAME_STATES,
}
